=== katurina/task3.3_Filmanovich/src/main/resources/people.xsd
<xsd:schema xmlns="http://www.w3.org/2001/XMLSchema"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://epam.training.by/people"
            xmlns:tns="http://epam.training.by/people">
    <xsd:element name="people">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="person"
                             type="tns:Person"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="Person">
        <xsd:sequence>
            <xsd:element name="name" type="string"/> <!--type="tns:NameString"/>-->
            <xsd:element name="surname" type="string"/><!--type="tns:NameString"/>-->
            <xsd:element name="telephone" type="string"/><!--type="string"/>-->
            <xsd:element name="email" type="string"/><!--type="tns:EmailString"/>-->
        </xsd:sequence>
    </xsd:complexType>
    <!--<xsd:simpleType name="NameString">-->
    <!--<xsd:restriction base="string">-->
    <!--<xsd:pattern value="[A-Za-z]*"/>-->
    <!--</xsd:restriction>-->
    <!--</xsd:simpleType>-->
    <!--<xsd:simpleType name="EmailString">-->
    <!--<xsd:restriction base="string">-->
    <!--<xsd:pattern value="[a-zA-Z0-9]*@[a-zA-Z0-9]*\.[a-zA-Z0-9]*"/>-->
    <!--</xsd:restriction>-->
    <!--</xsd:simpleType>-->
</xsd:schema>

=== katurina/task3.3_Filmanovich/src/main/resources/people.xml
<?xml version="1.0" encoding="UTF-8" ?>
<people xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://epam.training.by/people"
         xsd:schemaLocation="http://epam.training.by/people people.xsd">
    <person>
        <name>Ivan</name>
        <surname>Ivanov</surname>
        <telephone>+375363968524</telephone>
        <email>ivanov@a.a</email>
    </person>
    <person>
        <name>Bob</name>
        <surname>Petrov</surname>
        <telephone>+375869514586</telephone>
        <email>bob@s.com</email>
    </person>
    <person>
        <name>Linda</name>
        <surname>Sidorava</surname>
        <telephone>+375696854212</telephone>
        <email>linda@lin.da</email>
    </person>
    <person>
        <name>Willim</name>
        <surname>Black</surname>
        <telephone>+375896542342</telephone>
        <email>will@black.a</email>
    </person>
    <person>
        <name>Mark</name>
        <surname>Fry</surname>
        <telephone>+375 29 68 598 25</telephone>
        <email>mark@gmail.com</email>
    </person>
    <person>
        <name>Ella</name>
        <surname>White</surname>
        <telephone>+375 89 698 52 54</telephone>
        <email>white@gmail.com</email>
    </person>
    <person>
        <name>Stive</name>
        <surname>Suite</surname>
        <telephone>+375 29 368 52 54</telephone>
        <email>suieer@gmail.com</email>
    </person>
    <person>
        <name>Rimma</name>
        <surname>Fry</surname>
        <telephone>+375 33 687 45 12</telephone>
        <email>grey@gmail.com</email>
    </person>
    <person>
        <name>Kira</name>
        <surname>Krushtail</surname>
        <telephone>+375 39 365 32 23</telephone>
        <email>krushtail.kira@gmail.com</email>
    </person>
    <person>
        <name>Mirk</name>
        <surname>Morisons</surname>
        <telephone>+375 33 21 12 152</telephone>
        <email>maison@g.com</email>
    </person>
</people>
